# Generated by Django 3.0.6 on 2020-09-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('governorate', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=20)),
                ('job', models.CharField(max_length=50)),
            ],
        ),
    ]
