# Generated by Django 3.0.6 on 2020-09-28 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts_API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='job',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
