# Generated by Django 3.0.6 on 2020-09-30 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts_API', '0002_auto_20200929_0015'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClintOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cus_name', models.CharField(max_length=255)),
                ('cus_phone', models.CharField(max_length=255)),
                ('tech_phone', models.CharField(max_length=255)),
                ('o_desc', models.CharField(max_length=255)),
                ('o_date', models.CharField(max_length=255)),
                ('tech_name', models.CharField(max_length=255)),
                ('o_status', models.BooleanField(default=False)),
                ('o_excute_date', models.CharField(max_length=255)),
                ('o_governorate', models.CharField(max_length=255)),
                ('o_region', models.CharField(max_length=255)),
            ],
        ),
    ]
