# Generated by Django 3.0.6 on 2020-10-01 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts_API', '0003_clintorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clintorder',
            name='o_status',
            field=models.CharField(max_length=255),
        ),
    ]
